config/routes.rb
Rails.application.routes.draw do
  root to:'static_pages#home'

  controller :users do
    resources :users, except: [:index] do
      member do
        get :setting
        patch :email_update, :password_update
      end
    end
  end

  controller :sessions do
    get '/login', to: 'sessions#new'
    post '/login', to: 'sessions#create'
    delete 'logout', to: 'sessions#destroy'
  end

  controller :logs do
    resources :logs, except: [:destroy, :index]
  end

  controller :bodies do
    resources :bodies, only: [:index, :new, :create] do
      member do
        get :weight_show, :fat_percentage_show
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/body.rb
class Body < ApplicationRecord
  validates :date, presence: true
  validates :length, presence: true, numericality: { greater_than: 100}
  validates :weight, presence: true, numericality: { greater_than: 10}
  validates :fat_percentage, numericality: { greater_than: 1, less_than: 70}, allow_nil: true
  belongs_to :user

  def calculate_bmi
    (weight / ((length / 100) * (length/100))).round(1)
  end
end

app/models/log.rb
class Log < ApplicationRecord
  validates :training_day, presence: true
  validates :training_title, presence: true, length: { maximum: 20 }
  validates :comment, length: { maximum: 400 }

  belongs_to :user
  has_many :menus, inverse_of: :log
  accepts_nested_attributes_for :menus, reject_if: :all_blank, allow_destroy: true
end

app/models/menu.rb
class Menu < ApplicationRecord
  validates :training_event, presence: true, length: { maximum: 20 }
  belongs_to :log, inverse_of: :menus

  def calculate_1rm
    rm = training_weight * (1 + reps / 40.to_f)
  end
end

app/models/profile.rb
class Profile < ApplicationRecord
  validates :user_profile, length: { maximum: 400 }

  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }

  validates :name, presence: true, length: { maximum: 30 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
              format: { with: VALID_EMAIL_REGEX },
              uniqueness: { case_sensitive: false }

  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  has_one :profile, dependent: :destroy
  accepts_nested_attributes_for :profile
  has_many :logs
  has_many :bodies
  has_one_attached :avatar
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/bodies_controller.rb
class BodiesController < ApplicationController
  before_action :login_require

  def index
    @bodies = current_user.bodies
  end

  def weight_show
    #配列をJavascript用に変換
    @bodies_date    = current_user.bodies.pluck(:date).last(7).to_json.html_safe
    @bodies_weight  = current_user.bodies.pluck(:weight).last(7).to_json.html_safe
  end

  def fat_percentage_show
    @bodies_date    = current_user.bodies.pluck(:date).last(7).to_json.html_safe
    @bodies_fat_per = current_user.bodies.pluck(:fat_percentage).to_json.html_safe
  end

  def new
    @body = Body.new
  end

  def create
    @body = current_user.bodies.build(body_params)
    if @body.save
      flash[:success] = '記録しました。'
      redirect_to bodies_path
    else
      render 'new'
    end
  end

  private
      def body_params
        params.require(:body).permit(:date, :length, :weight, :fat_percentage)
      end
end

app/controllers/logs_controller.rb
class LogsController < ApplicationController
  before_action :login_require
  before_action :correct_user_logs, only: [:edit, :update]

  def show
    @log    = Log.find(params[:id])
    @menus  = @log.menus
    @user   = @log.user
  end

  def new
    @log = Log.new
    @log.menus.build
  end

  def create
    @log = current_user.logs.build(logs_params)
    if @log.save
      flash[:success] = '投稿しました。'
      redirect_to user_path(current_user)
    else
      render 'new'
    end
  end

  def edit
    @log = current_user.logs.find(params[:id])
  end

  def update
    @log = current_user.logs.find(params[:id])
    if @log.update(logs_params)
      flash[:success] = '更新しました。'
      redirect_to user_path(current_user)
    else
      render 'edit'
    end
  end

  private
      def logs_params
        params.require(:log).permit(:training_day, :training_title, :comment, menus_attributes: [:training_event, :training_weight, :reps, :training_time, :distance, :log_id, :destroy])
      end

      def correct_user_logs
        @log = current_user.logs.find_by(id: params[:id])
        if @log.nil?
          flash[:danger] = '更新権限がありません'
          redirect_to root_path
        end
      end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email].downcase)
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:success] = 'ログインしました。'
      redirect_to root_path
    else
      render 'new'
    end
  end

  def destroy
    reset_session
    flash[:success] = 'ログアウトしました。'
    redirect_to root_path
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :login_require, except: [:new, :create]
  before_action :correct_user, only: [:edit, :update, :destroy, :setting, :update_email, :update_password]

  def show
    @user     = User.find(params[:id])
    @profile  = @user.profile
    @logs     = @user.logs.order(created_at: :desc).page(params[:page]).per(5)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_create_params)
    if @user.save
      # ログインさせる
      session[:user_id] = @user.id
      flash[:success] = 'アカウントを作成しました。'
      redirect_to user_url(@user)
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    # すでに画像がある場合は、現在の画像をデフォルトでセット
    @user.avatar.attach(params[:user][:avatar]) if params[:user][:avatar]
    if @user.update(user_update_params)
      flash[:success] = 'アカウントを更新しました。'
      redirect_to user_url(@user)
    else
      render 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:success] = 'アカウントを削除しました。'
    redirect_to root_url
  end

  def setting
    @user = User.find(params[:id])
  end

  def email_update
    @user = User.find(params[:id])
    if @user.update(user_email_update_params)
      flash[:success] = 'メールアドレスを更新しました。'
      redirect_to user_url(@user)
    else
      render 'setting'
    end
  end

  def password_update
    @user = User.find(params[:id])
    # 現在のアドレスが一致しているのか照合
    if @user && @user.authenticate(params[:user][:old_password])
      if @user.update(user_password_update_params)
        flash[:success] = 'パスワードを更新しました。'
        redirect_to user_url(@user)
      else
        render 'setting'
      end
    else
      render 'setting'
    end
  end

  private
      def user_create_params
        params.require(:user).permit(:name,:email, :password, :password_confirmation)
      end

      def user_update_params
        params.require(:user).permit(:avatar, :name, profile_attributes: [:user_profile, :gim_training, :house_training,:weight_training, :bodyweight_training, :diet, :body_make, :power])
      end

      def user_email_update_params
        params.require(:user).permit(:email)
      end

      def user_password_update_params
        params.require(:user).permit(:password, :password_confirmation)
      end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = '')
    base_title = 'Motions'
    if page_title.empty?
      base_title
    else
      page_title + ' | ' + base_title
    end
  end
end

app/helpers/bodies_helper.rb
module BodiesHelper
end

app/helpers/logs_helper.rb
module LogsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def login_require
    redirect_to login_path unless current_user
  end

  def correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      flash[:danger] = '更新権限がありません'
      redirect_to root_path
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bodies/fat_percentage_show.html.erb
<% provide(:title, '体脂肪率グラフ') %>

<div id='bodies_fat_per_show'>
  <h1>- 体脂肪データ -</h1>
  <%= link_to '一覧', bodies_path, class: 'return-index' %>
  <canvas id='linechart' width='800' height='400'></canvas>
  <script>
    var ctx = document.getElementById('linechart');
    var linechart = new Chart(ctx, {
      type: 'line',
      data: {
        labels: <%= @bodies_date %>,
        datasets: [
          {
            label: '体脂肪',
            borderColor: 'blue',
            fill: false,
            data: <%= @bodies_fat_per %>,
          },
        ]
      },
    });
  </script>
</div>

app/views/bodies/index.html.erb
<% provide(:title, '個人データ') %>

<div id='bodies_index'>
  <h1>- 個人データ -</h1>
  <div class='index_link_area'>
    <%= link_to '体重グラフ', weight_show_body_path(current_user), class: 'btn' %>
    <%= link_to '体脂肪グラフ', fat_percentage_show_body_path(current_user), class: 'btn' %>
  </div>
  <div class='table-area'>
    <table class="table table-bordered">
      <thead class="thead-dark">
        <tr>
          <th>日付</th>
          <th>体重</th>
          <th>体脂肪率</th>
          <th>BMI</th>
        </tr>
      </thead>
      <tbody>
        <% @bodies.each do |body| %>
        <tr>
          <td><%= body.date %></td>
          <td><%= body.weight %> kg</td>
          <td><%= body.fat_percentage %> %</td>
          <td><%= body.calculate_bmi %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/bodies/new.html.erb
<% provide(:title, '身体データ記録' ) %>

<div id='bodies-new'>
  <h1>- 身体データ記録 -</h1>
  <%= form_with model: @body, local: true do |f| %>
    <%= render 'shared/errors_messages', object: f.object %>
    <div class='form-area'>
      <div class='form-group'>
        <%= f.label :date, '日付:', class: 'form-label col-md-3' %>
        <%= f.date_field :date, value: Time.now.strftime("%Y-%m-%d"), id: 'date' %>
      </div>
      <div class='form-group'>
        <%= f.label :length, '身長(cm):', class: 'form-label col-md-3' %>
        <%= f.text_field :length, class: 'body-form', id: 'user_length' %>
      </div>
      <div class='form-group'>
        <%= f.label :weight, '体重(kg):', class: 'form-label col-md-3' %>
        <%= f.text_field :weight, class: 'body-form', id: 'user_weight' %>
      </div>
      <div class='form-group'>
        <%= f.label :fat_percentage, '体脂肪率(%):', class: 'form-label col-md-3' %>
        <%= f.text_field :fat_percentage, class: 'body-form', id: 'user_fat_percentage' %>
      </div>
      <%= f.submit '記録', class: 'btn' %>
    </div>
  <% end %>
</div>

app/views/bodies/weight_show.html.erb
<% provide(:title, '体重グラフ') %>

<div id='bodies_weight_show'>
  <h1>- 体重データ -</h1>
  <%= link_to '一覧', bodies_path, class: 'return-index' %>
  <canvas id='linechart' width='800' height='400'></canvas>
  <script>
    var ctx = document.getElementById('linechart');
    var date_data = <%= @bodies_date %>
    var weight_data = <%= @bodies_weight %>
    var linechart = new Chart(ctx, {
      type: 'line',
      data: {
      labels: date_data,
      datasets: [
        {
          label: '体重',
          borderColor: 'red',
          fill: false,
          data: weight_data,
        },
      ]
    },
   });
  </script>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <link href="https://fonts.googleapis.com/css?family=Bitter:400,700&display=swap" rel="stylesheet">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class='<%= controller.action_name %>'>
    <header>
      <nav class='navbar sticky-top navbar-dark'>
        <%= link_to 'Motions', root_path, class: 'navbar-brand' %>
        <ul class='nav nav-tab'>
          <% if current_user %>
            <li class='nav-item'>
              <%= link_to '新規ログ', new_log_path, class: 'nav-link' %>
            </li>
            <li class='nav-item'>
              <%= link_to '身体記録', new_body_path, class: 'nav-link' %>
            </li>
            <li class='nav-item'>
              <%= link_to 'マイページ', user_path(current_user), class: 'nav-link' %>
            </li>
            <li class='nav-item'>
              <%= link_to 'ログアウト', logout_path, method: :delete, data: { confirm: "ログアウトします。よろしいですか？" }, class: 'nav-link' %>
            </li>
          <% else %>
            <li class='nav-item'>
              <%= link_to 'アカウント作成', new_user_path, class: 'nav-link' %>
            </li>
            <li class='nav-item'>
              <%= link_to 'ログイン', login_path, class: 'nav-link' %>
            </li>
          <% end %>
        </ul>
      </nav>
    </header>
    <div class='container'>
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/logs/_menu_fields.html.erb
<div class='training-form nested-fields'>
  <div>
    <%= f.text_field :training_event, placeholder: '種目', class: 'form-control', id: 'training_event' %>
  </div>
  <span>×</span>
  <div>
    <%= f.text_field :training_weight, placeholder: '重量(kg)', class: 'form-control', id: 'training_weight' %>
  </div>
  <span>×</span>
  <div>
    <%= f.number_field :reps, min: 1, placeholder: '回数(reps)', class: 'form-control', id: 'reps' %>
  </div>
  <%= link_to_remove_association '削除', f, class: 'delet-key' %>
</div>

app/views/logs/edit.html.erb
<% provide(:title, 'トレーニング編集') %>

<div id='logs-edit'>
  <h1>- トレーニング ログ編集 -</h1>
  <%= render 'shared/logs_form' %>
</div>

app/views/logs/new.html.erb
<% provide(:title, 'トレーニング作成') %>

<div id='logs-new'>
  <h1>- トレーニング ログ作成 -</h1>
  <%= render 'shared/logs_form' %>
</div>

app/views/logs/show.html.erb
<% provide(:title, 'トレーニング詳細') %>

<div id='logs-show'>
  <h1>- トレーニング詳細 -</h1>
  <div class="card">
    <div class="card-header"><%= @log.training_day %>　[ <%= @user.name %> ]</div>
    <div class="card-body">
      <h4 class="card-title"><%= @log.training_title %></h4>
      <p class="card-text">
        <table class='table table-bordered table-sm'>
          <thead>
            <tr>
              <th>種目</th>
              <th>重量(kg)</th>
              <th>回数(reps)</th>
              <th>最大重量(1RM)</th>
            </tr>
          </thead>
          <% @menus.each do |menu| %>
            <tbody>
              <td><%= menu.training_event %></td>
              <td><%= menu.training_weight %></td>
              <td><%= menu.reps %></td>
              <td><%= menu.calculate_1rm if menu.training_weight && menu.reps %></td>
            </tbody>
          <% end %>
        </table>
      </p>
      <div class='comment-area'>
        ーコメントー
        <p class="card-text"><%= @log.comment %></p>
      </div>
      <% if @user == current_user %>
        <%= link_to '編集', edit_log_path(@log), class: 'btn btn-success' %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_errors_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_logs_form.html.erb
<%= form_with model: @log, local: true do |f| %>
  <%= render 'shared/errors_messages', object: f.object  %>
  <div class='form-group'>
    <%= f.label :training_day, '日付:', class: 'form-label' %>
    <%= f.date_field :training_day,value: Time.now.strftime("%Y-%m-%d"), class: 'col-md-2', id: 'training_day' %>
  </div>
  <div class='form-group'>
    <%= f.label :training_title, 'トレーニング部位:', class: 'form-label' %>
    <%= f.text_field :training_title, class: 'form-control col-md-4', id: 'training_title' %>
  </div>
  <div class='training-menu'>
    <h4>トレーニング内容:</h4>
    <%= f.fields_for :menus do |m| %>
      <%= render 'menu_fields', f: m  %>
    <% end %>
    <div id="links">
      <%= link_to_add_association '追加',f, :menus, class: 'btn' %>
    </div>
  </div>
  <div class='form-group'>
    <%= f.label :comment, 'コメント:', class: 'form-label' %>
    <%= f.text_field :comment, class: 'form-control', id: 'comment' %>
  </div>
  <%= f.submit '投稿', class: 'btn btn-dark' %>
<% end %>

app/views/static_pages/home.html.erb
<div id='home'>
  <h1>Today is the first day of the rest of your life.</h1>
  <p>今すぐ<span>Motions</span>を始めよう。</p>
  <div class='buttons-area'>
    <% unless current_user %>
      <%= link_to 'アカウント作成', new_user_path, class: 'btn' %>
      <%= link_to 'ログイン', login_path, class: 'btn' %>
    <% end %>
  <div>
</div>

app/views/users/edit.html.erb
<% provide(:title, 'プロフィール編集' ) %>

<div id='users-edit'>
  <h1>- プロフィール編集 -</h1>

  <%= form_with model: @user, local: true do |f| %>
    <%= render 'shared/errors_messages', object: f.object %>
    <div class='form-group'>
      <%= f.label :avatar, 'アイコン:', class: 'form-label' %>
      <%= f.file_field :avatar, class: 'form-control' %>
    </div>
    <div class='form-group'>
      <%= f.label :name, 'ユーザー名:', class: 'form-label'%>
      <%= f.text_field :name, class: 'form-control', id: 'user_name' %>
    </div>
    <%= f.fields_for :profile, @user.profile || Profile.new do |pf| %>
      <div class='form-group'>
        <%= pf.label :user_profile, 'プロフィール(400字以内):', class: 'form-label' %>
        <%= pf.text_area :user_profile, class: 'form-control', id: 'user_profile' %>
      </div>
      <div class='check-group'>
        <%= pf.label :category, '興味のある項目を選択(複数可):', class: 'check-label' %>
        <%= pf.check_box :gim_training, {} , true, false %>
        <label class='form-check-label'>ジムトレ</label>
        <%= pf.check_box :house_training, {}, true, false %>
        <label class='form-check-label'>家トレ</label>
        <%= pf.check_box :weight_training, {}, true, false %>
        <label class='form-check-label'>ウエイトトレーニング</label>
        <%= pf.check_box :bodyweight_training, {}, true, false %>
        <label class='form-check-label'>自重トレーニング</label>
        <%= pf.check_box :diet, {}, true, false %>
        <label class='form-check-label'>ダイエット</label>
        <%= pf.check_box :body_make, {}, true, false %>
        <label class='form-check-label'>ボディメイク</label>
        <%= pf.check_box :power, {}, true, false %>
        <label class='form-check-label'>パワー</label>
      </div>
    <% end %>
    <%= f.submit 'プロフィール更新', class: 'btn btn-dark' %>
  <% end %>
</div>

app/views/users/new.html.erb
<% provide(:title, 'アカウント作成') %>

<div id='users-new'>
  <h1>- アカウント作成 -</h1>
  <%= form_with model: @user, local: true do |f| %>
    <%= render 'shared/errors_messages', object: f.object %>
    <div class='form-group'>
      <%= f.label :name, 'ユーザー名:', class: 'form-label'%>
      <%= f.text_field :name, class: 'form-control ', id: 'user_name' %>
    </div>
    <div class='form-group'>
      <%= f.label :email, 'メールアドレス:', class: 'form-label' %>
      <%= f.email_field :email, class: 'form-control', id: 'user_email' %>
    </div>
    <div class='form-group'>
      <%= f.label :password, 'パスワード:', class: 'form-label' %>
      <%= f.password_field :password, class: 'form-control', id: 'user_password' %>
    </div>
    <div class='form-group'>
      <%= f.label :password_confirmation, 'パスワード(確認):', class: 'form-label' %>
      <%= f.password_field :password_confirmation, class: 'form-control', id: 'password_confirmation' %>
    </div>
    <%= f.submit 'アカウント作成', class: 'btn btn-dark' %>
  <% end %>
</div>

app/views/users/setting.html.erb
<% provide(:title, 'ユーザー設定') %>

<div id='users-setting'>
  <h1>- メールアドレス変更 -</h1>
  <%= form_with model: @user, url: email_update_user_path(@user), local: true do |f| %>
    <div class='form-group'>
      <%= f.label :email, '新しいメールアドレス:', class: 'form-label' %>
      <%= f.email_field :email, class: 'form-control', id: 'user_email' %>
    </div>
    <%= f.submit 'メールアドレス更新', class: 'btn btn-dark' %>
  <% end %>

  <h1>- パスワード変更 -</h1>
  <%= form_with model: @user, url: password_update_user_path(@user), local: true do |f| %>
    <div class='form-group'>
      <%= f.label :old_password, '現在のパスワード:', class: 'form-label' %>
      <%= f.password_field :old_password, class: 'form-control', id: 'old_password' %>
    </div>
    <div class='form-group'>
      <%= f.label :new_password, '新しいパスワード:', class: 'form-label' %>
      <%= f.password_field :password, class: 'form-control', id: 'new_password' %>
    </div>
    <div class='form-group'>
      <%= f.label :password_confirmation, '新しいパスワード(確認):', class: 'form-label' %>
      <%= f.password_field :password_confirmation, class: 'form-control', id: 'new_password_confirmation' %>
    </div>
    <%= f.submit 'パスワード更新', class: 'btn btn-dark' %>
  <% end %>
</div>

app/views/users/show.html.erb
<% provide(:title, 'ユーザーページ') %>
<div id='users-show'>
<h1>- [ <%= @user.name %> ] -</h1>
<div class='show-content'>
  <div class='left-side'>
    <div class='user-img'>
      <%= image_tag @user.avatar if @user.avatar.attached? %>
    </div>
    <p class='user-name'><%= @user.name %></p>
    <% unless @profile.nil? %>
      <p class='user-profile'><%= @profile.user_profile %></p>
      <div class='user-category'>
        <p>カテゴリー:</p>
        <% if @user.profile.gim_training %>
          <p class='category-item'>ジムトレ</p>
        <% end %>
        <% if @user.profile.house_training %>
          <p class='category-item'>家トレ</p>
        <% end %>
        <% if @user.profile.weight_training %>
          <p class='category-item'>ウエイトトレーニング</p>
        <% end %>
        <% if @user.profile.bodyweight_training %>
          <p class='category-item'>自重トレーニング</p>
        <% end %>
        <% if @user.profile.diet %>
          <p class='category-item'>ダイエット</p>
        <% end %>
        <% if @user.profile.body_make %>
          <p class='category-item'>ボディメイク</p>
        <% end %>
        <% if @user.profile.power %>
          <p class='category-item'>パワー</p>
        <% end %>
      </div>
    <% end %>
    <% if @user == current_user %>
      <div class='show-link'>
        <%= link_to '身体記録', bodies_path, class: 'show-setting' %>
        <%= link_to 'プロフィール編集', edit_user_path(@user), class: 'show-setting' %>
        <%= link_to '設定', setting_user_path(@user), class: 'show-setting' %>
        <%= link_to 'ユーザー削除', @user, method: :delete, data: { confirm: 'アカウントを削除します。よろしいですか？' }, class: 'show-setting' %>
      </div>
    <% end %>
  </div>
  <div class='right-side'>
    <p class='title'>- トレーニング履歴 -</p>
    <% @logs.each do |log| %>
      <div class="card">
        <div class="card-body">
          <h4 class="card-title"><%= log.training_day %></h4>
          <p class="card-text"> <%= log.training_title %></p>
          <%= link_to '詳細', log_path(log), class: 'btn' %>
        </div>
      </div>
    <% end %>
    <%= paginate @logs %>
    <%= page_entries_info @logs %>
  </div>
</div>